### ISSUE TITLE
您好，想将您的项目作为练习demo

### ISSUE THREAD

**Issue by lanny-zhang** [YoneChen/WebVR-chatroom#1]
再window下运行npm run client时报错
 webvr-chatroom@3.3.0 client F:\WebVR-chatroom                                                    
 NODE_ENV=development webpack-dev-server --mode development --config ./client/webpack.config.js   
                                                                                                  
NODE_ENV' 不是内部或外部命令，也不是可运行的程序                                                                     
批处理文件。                                                                                            
pm ERR! code ELIFECYCLE                                                                           
pm ERR! errno 1                                                                                   
pm ERR! webvr-chatroom@3.3.0 client: `NODE_ENV=development webpack-dev-server --mode development -
ck.config.js`                                                                                     
pm ERR! Exit status 1                                                                             
pm ERR!                                                                                           
pm ERR! Failed at the webvr-chatroom@3.3.0 client script.                                         
pm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
                                                                                                  
pm ERR! A complete log of this run can be found in:                                               
pm ERR!     C:\Users\ZhangLN\AppData\Roaming\npm-cache\_logs\2019-04-14T05_56_12_119Z-debug.log   

但是mac下就没有问题，能帮忙看下是什么问题吗，谢谢！

**Comment by YoneChen** [comment]
windows下需安装cross-env，npm install --save-dev cross-env
